//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Producto()
        {
            this.DetalleVenta = new HashSet<DetalleVenta>();
        }
    
        public int idProducto { get; set; }
        public Nullable<int> codProducto { get; set; }
        public string nombre { get; set; }
        public int idCategoria { get; set; }
        public int stock { get; set; }
        public int stockMinimo { get; set; }
        public int idProveedor { get; set; }
        public Nullable<decimal> precioVenta { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
