//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Venta()
        {
            this.DetalleVenta = new HashSet<DetalleVenta>();
        }
    
        public int idVenta { get; set; }
        public int idTipoFactura { get; set; }
        public int idUsuario { get; set; }
        public int idCliente { get; set; }
        public int idFormaPago { get; set; }
        public Nullable<System.DateTime> fechaAlta { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleVenta> DetalleVenta { get; set; }
        public virtual FormaPago FormaPago { get; set; }
        public virtual TipoFactura TipoFactura { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
